"""HTML renderer — converts assembled Markdown to styled HTML."""

import logging
from pathlib import Path

import markdown

logger = logging.getLogger(__name__)

CSS = """
body {
    font-family: Calibri, 'Segoe UI', Arial, sans-serif;
    line-height: 1.7;
    max-width: 960px;
    margin: 40px auto;
    padding: 20px;
    color: #333;
    background: #f5f5f5;
}
.container {
    background: white;
    padding: 50px 60px;
    box-shadow: 0 0 20px rgba(0,0,0,0.08);
    border-radius: 4px;
}
h1 {
    color: #003366;
    font-size: 28px;
    border-bottom: 3px solid #003366;
    padding-bottom: 12px;
    margin: 40px 0 20px 0;
}
h2 {
    color: #003366;
    font-size: 22px;
    margin: 35px 0 15px 0;
    border-left: 4px solid #003366;
    padding-left: 14px;
}
h3 {
    color: #1a4d80;
    font-size: 18px;
    margin: 25px 0 10px 0;
}
h4 {
    color: #336699;
    font-size: 15px;
    margin: 20px 0 8px 0;
}
p {
    margin: 12px 0;
    text-align: justify;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin: 20px 0;
    font-size: 14px;
}
th {
    background: #003366;
    color: white;
    padding: 10px 12px;
    text-align: left;
    font-weight: 600;
}
td {
    padding: 8px 12px;
    border-bottom: 1px solid #ddd;
}
tr:nth-child(even) {
    background: #f8f9fa;
}
tr:hover {
    background: #e8f0fe;
}
ul, ol {
    margin: 10px 0;
    padding-left: 28px;
}
li {
    margin: 4px 0;
}
blockquote {
    border-left: 4px solid #003366;
    margin: 20px 0;
    padding: 10px 20px;
    background: #f8f9fa;
    color: #555;
    font-style: italic;
}
strong {
    color: #1a3a5c;
}
hr {
    border: none;
    border-top: 2px solid #003366;
    margin: 50px 0;
}
code {
    background: #f0f0f0;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 13px;
}
.report-footer {
    text-align: center;
    color: #999;
    font-size: 12px;
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #eee;
}
@media print {
    body {
        background: white;
        margin: 0;
        padding: 0;
    }
    .container {
        box-shadow: none;
        padding: 20px;
    }
    hr {
        page-break-after: always;
        border: none;
        margin: 0;
    }
    h1, h2, h3 {
        page-break-after: avoid;
    }
    table {
        page-break-inside: avoid;
    }
}
"""


class HtmlRenderer:
    """Render Markdown to styled HTML with professional CSS."""

    def render(self, markdown_content: str, output_path: Path, title: str = "") -> Path:
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Convert Markdown to HTML using python-markdown with extensions
        md = markdown.Markdown(
            extensions=[
                "tables",
                "toc",
                "smarty",
                "sane_lists",
            ],
            output_format="html5",
        )
        body_html = md.convert(markdown_content)

        # Build full HTML document
        display_title = title or "Report"
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{display_title}</title>
    <style>
{CSS}
    </style>
</head>
<body>
    <div class="container">
        {body_html}
        <div class="report-footer">
            Generated by US Bulk Supply Chain Reporting Platform
        </div>
    </div>
</body>
</html>"""

        output_path.write_text(html, encoding="utf-8")
        logger.info("Wrote HTML: %s (%d chars)", output_path, len(html))
        return output_path
